#!/bin/bash
set -e

echo "[+] Applying rolling update for blue deployment..."
kubectl apply -f blue_deployment.yaml

echo "[+] Monitoring rollout..."
kubectl rollout status deployment/messaging-blue

echo "[+] Running downtime test (Ctrl + C to stop)..."
while true; do
    curl -s http://$(minikube ip):8000/ > /dev/null
    echo "Request OK"
    sleep 1
done

echo "[+] Checking pods..."
kubectl get pods
