#!/bin/bash
set -e

echo "[+] Applying blue version..."
kubectl apply -f blue_deployment.yaml

echo "[+] Applying green version..."
kubectl apply -f green_deployment.yaml

echo "[+] Checking logs for green version..."
GREEN_POD=$(kubectl get pods -l app=messaging-green -o jsonpath="{.items[0].metadata.name}")
kubectl logs $GREEN_POD
