"""
Django settings for chats project.

Generated by Django and configured for ALX Backend Python project.
Middleware configuration for Django-Middleware-0x03 project.
"""

import os
from pathlib import Path

# =====================
# PATH CONFIGURATION
# =====================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =====================
# SECURITY CONFIGURATION
# =====================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here-change-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Hosts allowed to connect to the application
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']

# =====================
# APPLICATION DEFINITION
# =====================

# Django built-in applications
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Custom applications
    'chats',  # Our main chat application
]

# =====================
# MIDDLEWARE CONFIGURATION
# =====================

MIDDLEWARE = [
    # Django built-in middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # ==========================================
    # CUSTOM MIDDLEWARE FOR ALX PROJECT TASKS
    # ==========================================
    
    # Task 1: Request Logging Middleware
    # Logs each user's requests to a file with timestamp, user, and path
    'chats.middleware.RequestLoggingMiddleware',
    
    # Task 2: Time Restriction Middleware  
    # Restricts access to chat during certain hours (9 PM to 6 AM)
    'chats.middleware.RestrictAccessByTimeMiddleware',
    
    # Task 3: Rate Limiting Middleware
    # Limits number of chat messages per user IP address (5 messages per minute)
    'chats.middleware.OffensiveLanguageMiddleware',
    
    # Task 4: Role Permission Middleware
    # Checks user's role (admin/moderator) before allowing specific actions
    'chats.middleware.RolePermissionMiddleware',
]

# =====================
# URL CONFIGURATION
# =====================

ROOT_URLCONF = 'chats.urls'

# =====================
# TEMPLATE CONFIGURATION
# =====================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# =====================
# WSGI CONFIGURATION
# =====================

WSGI_APPLICATION = 'chats.wsgi.application'

# =====================
# DATABASE CONFIGURATION
# =====================

# SQLite database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# =====================
# PASSWORD VALIDATION
# =====================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =====================
# INTERNATIONALIZATION
# =====================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# =====================
# STATIC FILES (CSS, JavaScript, Images)
# =====================

STATIC_URL = '/static/'

# =====================
# DEFAULT PRIMARY KEY FIELD TYPE
# =====================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================
# CUSTOM CONFIGURATION FOR PROJECT MIDDLEWARE
# ==========================================

# Cache configuration for Task 3: Rate Limiting Middleware
# Uses local memory cache to track message counts per IP address
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Logging configuration for Task 1: Request Logging Middleware
# Logs requests to 'requests.log' file with timestamp and request details
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s - %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'requests.log',  # File where requests will be logged
            'formatter': 'standard',
        },
    },
    'loggers': {
        # Custom logger for request logging middleware
        'request_logger': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# =====================
# END OF CONFIGURATION
# =====================
